francisdb/vpxtool

.editorconfig, Cargo.lock, Cargo.toml, README.md, src/main.rs
Replaced the `// TODO figment` statement with very basic configuration. If the executable isnt found with the hardcoded path, it will just ask the user to give an executable path.
=> Added config and the previous code for executable detection.

Cargo.lock, Cargo.toml, src/frontend.rs
=> fix: check if vpinball executable is executable

Cargo.lock, Cargo.toml, src/config.rs, src/frontend.rs, src/indexer.rs, src/main.rs, src/vpx/mod.rs
=> feat: indexing rom names and checking availability

src/fixprint.rs, src/main.rs, src/vpx/expanded.rs
See https://github.com/rust-lang/rust/issues/46016
and the fix we applied https://github.com/rust-lang/rust/issues/46016#issuecomment-1242039016
=> fix: do not crash when piping to "head"

src/indexer.rs, src/lib.rs
=> fix: do not crash when roms folder is missing

Cargo.lock, Cargo.toml, src/lib.rs
vpinball 10.8 no longer uses pov files
=> chore: drop pov commands

src/fixprint.rs, src/lib.rs
=> fix: directb2s extract

src/patcher.rs
- Improve DT / ST variable detection
- Improve class inserting and fall back to end of file
fixes #175
=> fix: improve DT/STArray patching

src/indexer.rs
=> feat: improve gamename detection

src/patcher.rs
=> fix: DT/STArray keep target list

src/indexer.rs
for https://www.vpforums.org/index.php?app=downloads&showfile=17058
=> fix: pinmame requirement detection improved

src/frontend.rs, src/patcher.rs
Some tables come with a script that has mixed line endings. These can be `CRLF` (win), `LF` (unix) and even `CR` ???
This causes and the parser/compiler being confused and reporting errors at strange line numbers compared to what editors show.
This feature will unify line endings to vbscript standard `CRLF`
For an example see the patch for [Aztec (Williams 1976) 1.3](https://www.vpforums.org/index.php?app=downloads&showfile=15768) at https://github.com/jsm174/vpx-standalone-scripts/pull/216
=> feat: unify line endings

Cargo.lock, Cargo.toml, src/config.rs, src/frontend.rs, src/indexer.rs, src/lib.rs
fixes #152 local roms
fixes #190 Read VPinballX.ini
partly implements #136 (b2s indicator)
=> feat: local rom indexing

src/indexer.rs
=> fix: lowercase rom lookup

src/frontend.rs, src/patcher.rs
=> feat: prompt on table launch failure

.github/workflows/release.yml
=> feat: release archive contains version

src/lib.rs
=> feat: Show version when run without args

Cargo.lock, Cargo.toml, src/config.rs, src/lib.rs
=> feat: extract and assemble vpx files

src/frontend.rs, src/indexer.rs, src/lib.rs
continuation of #266 
To change table name fist do `Info > Edit` and then `Force reload`
=> feat: info edit/reload/diff in frontend

src/indexer.rs
=> fix: improve gamename detection

src/lib.rs
=> fix: extract over existing folder

Cargo.lock, Cargo.toml, src/frontend.rs
fixes #273
Unfortunately the fuzzy search widget I use has some issues
https://github.com/console-rs/dialoguer/issues/312
https://github.com/console-rs/dialoguer/issues/313
=> feat: search

src/frontend.rs, src/indexer.rs
closes  #282
However does not implement the requested clearing of the list on restart
=> feat: recently added tables

Cargo.lock, Cargo.toml, README.md, src/config.rs, src/frontend.rs, src/lib.rs
=> feat: configuring a text editor

Cargo.lock, Cargo.toml
=> fix: bmp export/import

src/frontend.rs
Select first table on open in recent playlist
=> feat: recent select first

src/lib.rs
=> feat: images to webp

src/indexer.rs
=> fix(indexer): ignore __MACOSX and .git folders

Cargo.lock
Fixes issue where image-webp would have issues reading certain photoshop webp files
=> build(deps): transitive dependency updates

Cargo.lock, Cargo.toml, src/frontend.rs, src/lib.rs
=> fix: improve io error handling for script operations

Cargo.lock, Cargo.toml, README.md, src/lib.rs
=> feat: VPURemix patching

README.md, src/indexer.rs, src/lib.rs
=> feat: romname command

Cargo.lock, Cargo.toml, src/frontend.rs, src/lib.rs
* show on console
* edit in frontend
=> feat: basic dip switch functionality

Cargo.lock, Cargo.toml, src/lib.rs
=> fix: ls showing gameitems

src/frontend.rs, src/indexer.rs, src/lib.rs
=> feat: handle global roms like local ones

src/indexer.rs, src/lib.rs
=> fix: make sure temp files are always cleaned up

Cargo.lock, shared/src/indexer.rs, vpxgui/Cargo.toml, vpxgui/src/event_channel.rs, vpxgui/src/guifrontend.rs, vpxgui/src/loading.rs, vpxgui/src/wheel.rs
- no longer uses egui
- shows table load progress
=> feat(gui): improve loading screen

vpxtool_gui/src/guifrontend.rs, vpxtool_gui/src/main.rs, vpxtool_gui/src/windowing.rs, vpxtool_shared/src/vpinball_config.rs
=> fix: windowing for desktop mode

vpxtool_cli/src/frontend.rs, vpxtool_shared/src/vpinball_config.rs
But does not work. See https://github.com/vpinball/vpinball/issues/2149
=> feat: also position the new DMD window

vpxtool_cli/src/lib.rs
Dropping the idea of having and advanced text frontend for now.
somewhat related to #131
=> chore(cli): remove simplefrontend

Cargo.lock, vpxtool_gui/Cargo.toml, vpxtool_gui/src/diagnostic/mod.rs, vpxtool_gui/src/diagnostic/system_information_diagnostics_plugin.rs, vpxtool_gui/src/guifrontend.rs, vpxtool_gui/src/lib.rs
It's no longer maintained so we drop it.
=> chore: drop bevy_mini_fps

vpxtool_cli/src/lib.rs
See also https://github.com/jsm174/vpx-standalone-scripts/pull/362 but not removing the context for now
=> feat(cli): hide path in diff

vpxtool_cli/src/lib.rs
=> fix: allow editing an invalid config

vpxtool_cli/src/frontend.rs, vpxtool_cli/src/lib.rs, vpxtool_gui/src/guifrontend.rs, vpxtool_gui/src/loading.rs, vpxtool_shared/src/config.rs, vpxtool_shared/src/indexer.rs
=> feat: local nvram from vpinball config and vpx_config config setting

vpxtool_cli/src/frontend.rs
* Add an option to edit the main vpinball config
* Ask the user if he want to create the table
* Reset the console when the main menu is shown
* Reset the console when the table menu is shown
fixes #511 
fixes #510 
fixes #501
=> feat: edit main vpinball config, create table config

Cargo.lock, vpxtool_shared/Cargo.toml, vpxtool_shared/src/indexer.rs
This implements parallel indexing, set `RAYON_NUM_THREADS` env var to limit the number of threads that can be used.
closes #520
=> feat: parallel indexing

vpxtool_cli/src/frontend.rs
This is quite basic and just showing everything as json
To be improved later on
=> feat: show nvram contents

src/cli.rs
=> fix: --output-dir vbs file name was missing a part
